export const LOAD_ASSESSMENT_SUCCESS = 'codezi/LOAD_ASSESSMENT_SUCCESS'
export const LOAD_ASSESSMENT = 'codezi/LOAD_ASSESSMENT'

export const OPEN_ASSESSMENT_DIALOG = 'codezi/OPEN_ASSESSMENT_DIALOG'
export const CLOSE_ASSESSMENT_DIALOG = 'codezi/CLOSE_ASSESSMENT_DIALOG'

export const ADD_UPDATE_ASSESSMENT = 'codezi/ADD_UPDATE_ASSESSMENT'
export const ADD_UPDATE_ASSESSMENT_DONE = 'codezi/ADD_UPDATE_ASSESSMENT_DONE'
