// Customizer const
export const THEME_TYPE = 'THEME_TYPE'

export const THEME_OPTIONS = {
   1: 'THEME_TYPE_SEMI_DARK',
   2: 'THEME_TYPE_DARK',
   3: 'THEME_TYPE_LITE',
}

export const THEME_TYPE_LITE = 'THEME_TYPE_LITE'
export const THEME_TYPE_DARK = 'THEME_TYPE_DARK'
export const THEME_TYPE_SEMI_DARK = 'THEME_TYPE_SEMI_DARK'
export const CHANGE_THEME_TYPE = 'CHANGE_THEME_TYPE'

export const NAV_STYLE = 'NAV_STYLE'

export const NAV_STYLE_FIXED = 'NAV_STYLE_FIXED'
export const NAV_STYLE_MINI_SIDEBAR = 'NAV_STYLE_MINI_SIDEBAR'
export const NAV_STYLE_DRAWER = 'NAV_STYLE_DRAWER'
export const NAV_STYLE_NO_HEADER_MINI_SIDEBAR =
   'NAV_STYLE_NO_HEADER_MINI_SIDEBAR'
export const NAV_STYLE_NO_HEADER_EXPANDED_SIDEBAR =
   'NAV_STYLE_NO_HEADER_EXPANDED_SIDEBAR'

export const TAB_SIZE = 992
